In [1]:
# 1
import numpy as np

In [3]:
# 2
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# 3
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [125]:
# 4
arr_2d = np.zeros((10,10))

In [126]:
# 4
arr_length = arr_2d.shape[1]

In [127]:
# 4 
for i in range(arr_length):
    arr_2d[i]=i
    
arr_2d[5]

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [128]:
# 4
arr = [5.,5.,5.,5.,5.,5.,5.,5.,5.,5.]

In [129]:
# 4 두번 째 정답
np.array(arr)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [54]:
# 5
arr2 = np.arange(10,51)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [56]:
# 6
arr3 = np.arange(10,51,2)
arr3

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [31]:
# 7 
num = ([0,1,2],[3,4,5],[6,7,8])

In [33]:
np.array(num)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
# 8 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
# 9
np.random.rand(1)

array([0.92448646])

In [76]:
# 10
# 표준편차가 1인것 예를 들어 동전 앞뒤를 1000번 던지면 대략 500번 500번 가량 나온다는 뜻
np.random.randn(5,5)

array([[ 1.34534338, -0.91538129,  0.33980123, -1.25291167, -0.67159967],
       [ 0.75735457, -0.32004521,  2.28018816,  1.44266837,  1.68283766],
       [-0.53395316, -1.49077352, -0.76966412, -0.09650103, -0.53681289],
       [-1.23392195, -0.5061939 , -0.58618737, -0.86372365,  0.09586705],
       [-0.04373501, -0.47140355, -0.01365447, -1.14656357, -1.02499586]])

In [79]:
# 11
np.linspace(0.01,1,100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [80]:
# 12
np.random.rand(4,4)

array([[0.41621962, 0.13530435, 0.48315797, 0.22718731],
       [0.55673154, 0.62937779, 0.64554109, 0.02517403],
       [0.28955555, 0.05638081, 0.18365916, 0.00576381],
       [0.04595665, 0.00978302, 0.89236488, 0.24168222]])

In [87]:
# 13
mat = np.arange(1,26)

In [88]:
mat.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [152]:
# 14
print(np.array(mat)[11:15])
print(np.array(mat)[16:20])
print(np.array(mat[21:25]))

[12 13 14 15]
[17 18 19 20]
[22 23 24 25]


In [124]:
# 15
mat[19]

20

In [147]:
# 16
print(np.array(mat)[1:2])
print(np.array(mat)[6:7])
print(np.array(mat[11:12]))

[2]
[7]
[12]


In [153]:
# 17
np.array(mat)[20:25]

array([21, 22, 23, 24, 25])

In [154]:
# 18
np.array(mat)[15:25]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [160]:
# 19
mat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])