In [377]:
import numpy as np

In [378]:
arr2 = np.arange(11)

In [379]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [380]:
arr2 >= 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [381]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [382]:
arr2 > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [383]:
arr2 = np.arange(6)

In [384]:
arr2

array([0, 1, 2, 3, 4, 5])

In [385]:
arr2 = np.arange(0,11)

In [386]:
slice_of_arr2 = arr2[0:6]
# 부분복사

slice_of_arr2

array([0, 1, 2, 3, 4, 5])

In [387]:
slice_of_arr2[:]=99

In [388]:
slice_of_arr2

array([99, 99, 99, 99, 99, 99])

In [389]:
arr2

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [390]:
arr_copy = arr2.copy()

arr_copy
# 전체복사

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [391]:
arr_2d = ([5,10,15],[20,25,30],[35,40,45])

In [392]:
np.array(arr_2d)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [394]:
arr_2d = np.zeros((10,10))

In [395]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [396]:
arr_length = arr_2d.shape[1]


arr_length

10

In [426]:
for i in range(arr_length):
    arr_2d[i]=i
    
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [442]:
arr= np.arange(0,10)

In [443]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [444]:
arr *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [445]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [446]:
arr*0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [449]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [450]:
np.sqrt(arr)
# 루트

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])